/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarketcashiersystem;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author superuser
 */
public class CashierUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CashierUI.class.getName());

    /**
     * Creates new form CashierUI
     */
    public CashierUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        productNameText = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        priceText = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        basketTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        btnBread = new javax.swing.JButton();
        btnWater = new javax.swing.JButton();
        btnMilk = new javax.swing.JButton();
        btnEgg = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("SUPERMARKET CASHIER SYSTEM");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        productNameText.setText("Product Name:");

        productNameField.addActionListener(this::productNameFieldActionPerformed);

        priceText.setText("Price:");

        priceField.addActionListener(this::priceFieldActionPerformed);

        addButton.setBackground(new java.awt.Color(102, 255, 102));
        addButton.setText("Add to Basket");
        addButton.addActionListener(this::addButtonActionPerformed);

        basketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Final Price"
            }
        ));
        jScrollPane1.setViewportView(basketTable);

        jLabel2.setText("Total:");

        removeButton.setBackground(new java.awt.Color(255, 51, 51));
        removeButton.setText("Remove Selected");
        removeButton.addActionListener(this::removeButtonActionPerformed);

        btnBread.setText("Add Bread (12)");
        btnBread.addActionListener(this::btnBreadActionPerformed);

        btnWater.setText("Add Water (5)");
        btnWater.addActionListener(this::btnWaterActionPerformed);

        btnMilk.setText("Add Milk (35)");
        btnMilk.addActionListener(this::btnMilkActionPerformed);

        btnEgg.setText("Add Egg (50)");
        btnEgg.addActionListener(this::btnEggActionPerformed);

        totalLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productNameText)
                            .addComponent(priceText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBread, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBread, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnWater, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNameText)
                            .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceText)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameFieldActionPerformed

    public void updateTotal() {
        double currentTotal = 0;
        // Tablodaki her satırı gezip 2. sütundaki (Final Price) değerleri toplar
        for (int i = 0; i < basketTable.getRowCount(); i++) {
            currentTotal += (double) basketTable.getValueAt(i, 2);
        }
        // Sonucu etikete yazdırır
        totalLabel.setText(String.format("%.2f", currentTotal));
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            // 1. Get data from text fields
            String name = productNameField.getText();
            double price = Double.parseDouble(priceField.getText());

            // 2. Use our Product class and calculate tax (Math Concept)
            Product p = new Product(name, price, "BAR-001");
            double finalPriceWithTax = p.calculateFinalPrice();

            // 3. Add to Table (Data in array form)
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) basketTable.getModel();
            model.addRow(new Object[]{p.getName(), p.getPrice(), finalPriceWithTax});
            // Genel toplamı hesapla
            double currentTotal = 0;
            for (int i = 0; i < basketTable.getRowCount(); i++) {
                currentTotal += (double) basketTable.getValueAt(i, 2); // Final Price sütununu topla
            }
            totalLabel.setText(String.format("%.2f", currentTotal));
            updateTotal();
            // 4. Clear fields for next entry
            productNameField.setText("");
            priceField.setText("");

        } catch (Exception e) {
            // Simple Exception Handling 
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric price!");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int selectedRow = basketTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) basketTable.getModel();
            model.removeRow(selectedRow);

            // Sildikten sonra toplamı tekrar hesaplat (Yukarıdaki toplam koduyla aynı)
            double currentTotal = 0;
            for (int i = 0; i < basketTable.getRowCount(); i++) {
                currentTotal += (double) basketTable.getValueAt(i, 2);
            }
            totalLabel.setText(String.format("%.2f", currentTotal));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product to remove!");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void btnBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBreadActionPerformed
        try {
            Product p = new Product("Bread", 12.0, "BREAD-001");
            double finalPrice = p.calculateFinalPrice();
            DefaultTableModel model = (DefaultTableModel) basketTable.getModel();
            model.addRow(new Object[]{p.getName(), p.getPrice(), finalPrice});
            updateTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBreadActionPerformed

    private void btnWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWaterActionPerformed
        try {
            Product p = new Product("Water", 5.0, "WATER-001");
            double finalPrice = p.calculateFinalPrice();
            DefaultTableModel model = (DefaultTableModel) basketTable.getModel();
            model.addRow(new Object[]{p.getName(), p.getPrice(), finalPrice});
            updateTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnWaterActionPerformed

    private void btnMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilkActionPerformed
        try {
            Product p = new Product("Milk", 35.0, "MILK-001");
            double finalPrice = p.calculateFinalPrice();
            DefaultTableModel model = (DefaultTableModel) basketTable.getModel();
            model.addRow(new Object[]{p.getName(), p.getPrice(), finalPrice});
            updateTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMilkActionPerformed

    private void btnEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEggActionPerformed
        try {
            Product p = new Product("Egg", 50.0, "EGG-001");
            double finalPrice = p.calculateFinalPrice();
            DefaultTableModel model = (DefaultTableModel) basketTable.getModel();
            model.addRow(new Object[]{p.getName(), p.getPrice(), finalPrice});
            updateTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEggActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CashierUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable basketTable;
    private javax.swing.JButton btnBread;
    private javax.swing.JButton btnEgg;
    private javax.swing.JButton btnMilk;
    private javax.swing.JButton btnWater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceText;
    private javax.swing.JTextField productNameField;
    private javax.swing.JLabel productNameText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
